---
# This is a basic workflow to help you get started with Actions
# rebased against upstream/sagitta

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the current branch
on: # yamllint disable-line rule:truthy
  push:
    branches: [ sagitta ]
  pull_request:
    branches: [ sagitta ]
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: 'No source specified'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install docker and prerequisites
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Set VERSION variable
        run: |
          echo "VERSION=1.4-$(date +%Y%m%d%H%M)-transficc" >> $GITHUB_ENV

#     - name: Pull in custom vyos-1x
#       run: |
#         cd $GITHUB_WORKSPACE/packages
#         wget https://github.com/TransFICC/vyos-1x/releases/latest/download/vyos-1x_amd64.deb -O vyos-1x_amd64.deb
#         echo "VYOS_1X_VERSION=$(dpkg-deb -I vyos-1x_amd64.deb | awk '/Version:/{print $2}')" >> $GITHUB_ENV

      - name: Build standard iso
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          docker run --rm --privileged -v $GITHUB_WORKSPACE:/vyos -w /vyos vyos/vyos-build:sagitta bash -c \
            "sudo make clean; sudo ./build-vyos-image iso --architecture amd64 --build-by sre@transficc.com --build-type release --version $VERSION \
            --custom-package 'krb5-pkinit lighttpd python3-apt tmux realmd kstart libpam-ldapd vim freeipa-client lighttpd-mod-deflate nslcd sssd' \
             ; ls -la ./ ; ls -la build/ ; sudo mv build/live-image-amd64.hybrid.iso vyos-$VERSION.iso;"
          pwd
          ls -l . build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload standard release asset
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vyos-${{ env.VERSION }}.iso
          asset_name: vyos.iso
          asset_content_type: application/x-iso9660-image
