---
# This is a basic workflow to help you get started with Actions
# rebased against upstream/current = e01283e75aaf21bc171b4aa791206b498380c1eb
# previously rebased against dc5e42b9daa97a35ab9fa4cb473b62b7abb146da

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the current branch
on: # yamllint disable-line rule:truthy
  push:
    branches: [ current ]
  pull_request:
    branches: [ current ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install docker and prerequisites
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Set VERSION variable
        run: |
          echo "VERSION=1.4-rolling-$(date +%Y%m%d%H%M)-transficc" >> $GITHUB_ENV

      - name: Update config.boot.default
        run: |
          echo Before
          find $GITHUB_WORKSPACE -name config.boot.default -ls
          cat <<CONFIG_BOOT_DEFAULT > $GITHUB_WORKSPACE/data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default
          system {
              host-name vyos
              login {
                  user vyos {
                      authentication {
                          encrypted-password $6$QxPS.uk6mfo$9QBSo8u1FkH16gMyAVhus6fU3LOzvLR9Z9.82m3tiHFAxTtIkhaZSWssSgzt4v4dGAL8rhVQxTg0oAG9/q11h/
                          plaintext-password ""
                      }
                  }
              }
              syslog {
                  global {
                      facility all {
                          level info
                      }
                      facility protocols {
                          level debug
                      }
                  }
              }
              ntp {
                  server "time1.vyos.net"
                  server "time2.vyos.net"
                  server "time3.vyos.net"
                  vrf mgmt
              }
              console {
                  device ttyS0 {
                      speed 115200
                  }
              }
              config-management {
                  commit-revisions 100
              }
          }

          service {
              lldp {
                  interface all {
                  }
              }
              ssh {
                  vrf mgmt
              }
          }

          vrf {
              bind-to-all
              name mgmt {
                  table 100
              }
          }

          interfaces {
              ethernet eth0 {
                  address dhcp
                  vrf mgmt
              }
              ethernet eth1 {
              }
              ethernet eth2 {
              }
              ethernet eth3 {
              }
              loopback lo {
              }
          }
          CONFIG_BOOT_DEFAULT
          echo After
          find $GITHUB_WORKSPACE -name config.boot.default -ls

      - name: Enable some additional services by default
        run: |
          echo <<EOSERVICES >> $GITHUB_WORKSPACE/data/live-build-config/hooks/live/18-enable-disable_services.chroot
          systemctl enable telegraf.service
          systemctl enable sssd.service
          systemctl enable nslcd.service
          systemctl enable pdns-recursor.service
          EOSERVICES

      - name: Build custom vyos-1x
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/vyos/vyos-1x.git
          cd vyos-1x
          ## customisations will go here

          # sshd_config
          sed -i -e '/^# User configurable section/i # Added freeipa config\n\n#' data/templates/ssh/sshd_config.j2
          sed -i -e '/^# Added freeipa config/a UsePAM yes' data/templates/ssh/sshd_config.j2
          sed -i -e '/^# Added freeipa config/a GSSAPIAuthentication yes' data/templates/ssh/sshd_config.j2
          sed -i -e 's/^ChallengeResponseAuthentication no/# &/' data/templates/ssh/sshd_config.j2
          sed -i -e '/^# Added freeipa config/a ChallengeResponseAuthentication yes' data/templates/ssh/sshd_config.j2
          sed -i -e '/^# Added freeipa config/a AuthorizedKeysCommandUser nobody' data/templates/ssh/sshd_config.j2
          sed -i -e '/^# Added freeipa config/a AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys' data/templates/ssh/sshd_config.j2

          # pdns-recursor
          mkdir -p ./src/etc/systemd/system/pdns-recursor.service.d
          cat <<EOPDNS_SERVICE > ./src/etc/systemd/system/pdns-recursor.service.d/override.conf
          [Service]
          User=root
          WorkingDirectory=
          WorkingDirectory=/run/powerdns
          RuntimeDirectory=
          RuntimeDirectory=powerdns
          RuntimeDirectoryPreserve=yes
          ExecStart=
          ExecStart=/bin/ip vrf exec mgmt /usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no --config-dir=/run/powerdns --socket-dir=/run/powerdns --setuid=pdns

          LimitMEMLOCK=8388608
          CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_CHOWN CAP_SYS_ADMIN CAP_NET_ADMIN CAP_DAC_OVERRIDE CAP_SETUID
          AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_CHOWN CAP_SYS_ADMIN CAP_NET_ADMIN CAP_DAC_OVERRIDE CAP_SETUID
          ProtectControlGroups=false
          RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
          EOPDNS_SERVICE

          # telegraf config
          ln -s /config/telegraf ./src/etc/telegraf
          mkdir -p ./src/etc/systemd/system/telegraf.service.d
          cat <<EOTELEGRAF_SERVICE > ./src/etc/systemd/system/telegraf.service.d/override.conf
          [Unit]
          After=vyos-router.service

          [Service]
          User=root
          ExecStart=
          ExecStart=/usr/sbin/ip vrf exec mgmt /sbin/runuser -u telegraf -- /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS
          RestartSec=10s

          [Install]
          WantedBy=
          WantedBy=vyos.target
          EOTELEGRAF_SERVICE

          # nslcd config
          mkdir -p ./src/etc/systemd/system/nslcd.service.d
          cat <<EONSLCD_SERVICE > ./src/etc/systemd/system/nslcd.service.d/override.conf
          [Service]
          ExecStart=
          ExecStart=/usr/bin/ip vrf exec mgmt

          ## end of customisations
          cd $GITHUB_WORKSPACE
          docker run --rm --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0 -v $GITHUB_WORKSPACE:/vyos -w /vyos vyos/vyos-build:current \
          bash -c "cd vyos-1x; make all; make deb"
          find . -name '*.deb' -ls
          cp ./vyos-1x_1.4*.deb packages/

      - name: Build standard iso
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          docker run --rm --privileged -v $GITHUB_WORKSPACE:/vyos -w /vyos vyos/vyos-build:current bash -c \
            "./configure --architecture amd64 --build-by sre@transficc.com --build-type release --version $VERSION-standard \
             --custom-package 'krb5-pkinit lighttpd python3-apt tmux realmd sssd libpam-ldapd nslcd kstart vim freeipa-client lighttpd-mod-deflate'; sudo make iso"
          mv $GITHUB_WORKSPACE/build/live-image-amd64.hybrid.iso vyos-$VERSION-standard.iso
          pwd
          ls -l . build

      - name: Build AWS iso
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          docker run --rm --privileged -v $GITHUB_WORKSPACE:/vyos -w /vyos vyos/vyos-build:current bash -c \
            "./configure --architecture amd64 --build-by sre@transficc.com --build-type release --version $VERSION-aws \
             --custom-package 'krb5-pkinit lighttpd python3-apt tmux realmd sssd libpam-ldapd nslcd kstart vim freeipa-client lighttpd-mod-deflate'; sudo make AWS"
          mv $GITHUB_WORKSPACE/build/live-image-amd64.hybrid.iso vyos-$VERSION-aws.iso
          pwd
          ls -l . build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload standard release asset
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vyos-${{ env.VERSION }}-standard.iso
          asset_name: vyos-standard.iso
          asset_content_type: application/x-iso9660-image

      - name: Upload AWS release asset
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vyos-${{ env.VERSION }}-aws.iso
          asset_name: vyos-aws.iso
          asset_content_type: application/x-iso9660-image
