---
name: Rebase Upstream
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 2 * * *"  # run nightly
  workflow_dispatch:  # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rebase with upstream
        uses: imba-tjd/rebase-upstream-action@0.5
        with:
          upstream: vyos/vyos-build
          branch: current
          depth: 0
